### ISSUE TITLE
Black - White Image on capturing screen

### ISSUE THREAD

**Issue by iradovanovic** [robotframework/SeleniumLibrary#839] opened 2017-06-23 14:12 UTC
Hi all,

since recently we have a problem with screenshots but only when the test is executed with Jenkins.
Captured image looks like this: left side is white, right is black. That is all. When I run manually on same maschine (VM) it works.  Any ideas?

**Comment by aaltat** [comment] 2017-06-23 14:42
Not really good ideas, haven't seen that one before. But I can make educated guesses. Is it a Windows or Linux that is running Jenkins? Does it have a display? Have you tried with different browsers? Have you updated Selenium and browser driver?

Also asking in user group would be good idea, because you get wider audience for your question.

**Comment by iradovanovic** [comment] 2017-06-23 14:54
Hi.
It is a Windows virtual machine (Win 8). Chrome driver and selenium up to date.
Since is running from Slave on VM there is a screen (with screen i mean, if you connect to that VM you will see browser and executions) We use only Chrome.

By user group you mean google group?

I wanted also here to report the problem.

**Comment by aaltat** [comment] 2017-06-23 16:25
If you logout then the display also dies and it affects also to the screen captures. In Windows 7 it is possible direct the login session to the console so that the display does not die. But I don't have any experience with Win 8.

Yes I was referring to the Google user group.

**Comment by aaltat** [comment] 2017-06-26 21:36
Did you get the problem solved?

**Comment by iradovanovic** [comment] 2017-06-26 21:42
Not yet. Today, i tried to import Library Browser and to use "Take Screenshot" from that one. Tomorrow i will check if is working with jenkins. I had a problem with image path.

**Comment by iradovanovic** [comment] 2017-06-29 06:29
Ok. New update. When i'm manually logged in to the VM and watching while robot is executing, then the image is captured. Otherwise is black | white image.

I have to find what is updated or changed.

**Comment by aaltat** [comment] 2017-06-29 10:30
In windows 7 I can do this: `tscon.exe RDP-Tcp#0 /dest:console` to divert to desktop to the console.

**Comment by willmiraglia** [comment] 2017-07-06 14:40
I'm seeing this issue too. It started about 10 days ago and I've not been able to figure out whats going on. It just started to occur overnight and I did not touch the configuration of my environment.

I now see blank screenshots in my reports when running Jenkins as a service and the tests are headless. ( doesn't happen if I log into the machine and run the tests with a display) - I can confirm it happens in Chrome at the moment. I've not been able to run headless tests yet with Firefox.

I changed jenkins service properties 'Allow service to interact with desktop' - but still didn't fix it. This was a long shot as previously screehshots worked fine without this set.

--------------------
OS-Windows Service 2012 R2 standard = x64 based PC
Chrome version: Version 59.0.3071.115 (Official Build) (64-bit)

cut ----------------
Jenkins version 2.60.1
ChromeDriver 2.30
robotframework (3.0.2)
robotframework-imaplibrary (0.2.3)
robotframework-ride (1.5.2.1)
robotframework-selenium2library (1.8.0)
robotframework-sshlibrary (2.1.2)
selenium (3.4.3)

![screen shot 2017-07-06 at 10 25 51 am](https://user-images.githubusercontent.com/13484541/27915924-a5a8acd4-6235-11e7-92a1-f6e33ae05d7d.png)

![screen shot 2017-07-06 at 10 39 25 am](https://user-images.githubusercontent.com/13484541/27916564-72a7f6a8-6237-11e7-9e89-2d3eada896e5.png)

**Comment by aaltat** [comment] 2017-07-06 15:05
I don't have any good advice to give, because I don't know a solution for this problem. Also I am not able to reproduce the problem.

Because the screen capture is really thin wrapper on top of the selenium, I don't think this is a Selenium2Library issue. To prove that assumption, are you able to write small Python script that call the same methods from selenium than the Selenium2Library would do when taking screen shot? If you are not able to write it, I can write it for you. Then you can run the script in your environment and we can see the results.

It might be good idea to also ask from the user group have someone else had the same problem and how they have solved the problem.

**Comment by iradovanovic** [comment] 2017-07-10 15:48
@willmiraglia Did you update anything in/from Jenkins ?

Did you maybe try FF ?

Now, i'm getting an idea to try with an older chrome version.

**Comment by willmiraglia** [comment] 2017-07-14 00:42
@aaltat - That's a good idea. If you could give me that script then I could try it?
@iradovanovic  I've not been able to get FF running yet via Jenkins headless. But I'm working on it. My thinking is this is also a chrome update problem perhaps, but installing older chrome versions can be a pain too. I'll look into it.

**Comment by iradovanovic** [comment] 2017-07-14 06:50
So, the chrome is a problem or just they are not compatible. After installing an older version of chrome (48) and an older chromedriver, everything is working again.

**Comment by aaltat** [comment] 2017-07-14 07:03
Here is code snippet:
```
from selenium import webdriver

driver = webdriver.Chrome()
driver.get("http://robotframework.org/")
assert "Robot" in driver.title
driver.save_screenshot('/path/to/robot.png')
driver.close()
```
Put it in a `script.py` file and run in from Jenkins. If it produces the same result, raise an issue to Selenium side.

**Comment by glipautomationuser1** [comment] 2017-07-17 22:58
@aaltat Thanks, I'll try that out.

**Comment by glipautomationuser1** [comment] 2017-07-17 23:00
@iradovanovic  Very Interesting, so it must be chrome. That would explain why the problem occurred over night, most likely after chrome updated. I'll try figure out how to downgrade chrome and test it too. Although 48 seems very old, I'll try downgrade incrementally until it works again.

**Comment by aaltat** [comment] 2017-07-31 15:58
Is this still a problem or can we close the issue. If we can close the issue, it would be nice to hear how the problem was solved.

**Comment by drumaster17** [comment] 2017-08-08 22:25
@aaltat Did you solve the problem ? because I'm also facing the issue

**Comment by aaltat** [comment] 2017-08-09 08:38
No, I am unable to reproduce the problem and therefore I am not able to fix it.

**Comment by aaltat** [comment] 2017-08-09 13:19
But you could my script from few posts above. If you get the same results with that Selenium script, then the problem is in Selenium. In that case you need to report that problem to the Selenium issue tracker.

**Comment by iradovanovic** [comment] 2017-08-17 14:41
Sry for the late response. I was on vacation. :)

We have a workaround with using fix version of chrome. 58 and disabled chrome update. Using last chrome webdriver. Also on other our VM where is used win7 and/or win10 the problem is not presented. Only Win 8.1.

**Comment by aaltat** [comment] 2017-08-20 06:37
Because Selenium2Library is a thin wrapper on top of the Selenium, this definitely feels like a Selenium bug. @iradovanovic please open a issue to the Selenium side.

@drumaster17 and @glipautomationuser1 have you found a solution to your problem?

**Comment by aaltat** [comment] 2017-08-31 16:16
Because this looks like problem in Selenium side, I am closing the issue.

**Closed as completed by aaltat** 2017-08-31 16:16 UTC

**Comment by iradovanovic** [comment] 2017-09-04 07:46
Maybe just update - since chrome releases the new update... the black/white
screenshots is not presented anymore!
