### ISSUE TITLE
how to switch to new window popup using robot framework ,if new window is not having title and name

### ISSUE THREAD

**Issue by tayyabalam19** [robotframework/SeleniumLibrary#1059] opened 2018-02-17 19:35 UTC

**Comment by aaltat** [comment] 2018-02-17 22:34
This is a support request and not a bug or feature request and it would be better to seek support from -[support channels](https://github.com/robotframework/SeleniumLibrary#support). Therefore I am closing the issue. 

But see [what this keyword](http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Get%20Window%20Handles) tell you and perform the window selection accordingly.

**Closed as completed by aaltat** 2018-02-17 22:34 UTC

**Comment by tayyabalam19** [comment] 2018-02-20 06:54
Thanks, i am able to implement **Get Window handles** keyword and its working
