### ISSUE TITLE
Capture Page Screenshot' could not be run on failure

### ISSUE THREAD

**Issue by cdasadiya** [robotframework/SeleniumLibrary#787] opened 2017-04-03 09:50 UTC
[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: Multiple keywords with name **'Capture Page Screenshot'** found. Give the full name of the keyword you want to use:
    **AppiumLibrary.Capture Page Screenshot
    Selenium2Library.Capture Page Screenshot**
I have got the issue while run the pybot demo_8_0_full_workflow.robot for odoo automation test case purpose

**Comment by aaltat** [comment] 2017-04-03 12:37
This is by design in Robot Framework and is explained in the Robot Framework user guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#handling-keywords-with-same-names

Because this is not a problem in Selenium2Library closing the issue.

**Closed as completed by aaltat** 2017-04-03 12:37 UTC
