### ISSUE TITLE
OpenBrowser(selenium) keyword not working in Ride 

### ISSUE THREAD

**Issue by Pallaviayalureddy** [robotframework/SeleniumLibrary#1610] opened 2020-06-22 04:55 UTC
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/MarketSquare/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by aaltat** [comment] 2020-06-22 05:57
I am assuming that this is about keyword documentation. I know the issue, It's because of the type hints in the arguments. But this is not a bug in the SeleniumLibrary, it's bug in the RIDE. Type hints are valid part of the Robot Framework library API and RIDE should be able to process or at least ignore the type hints. Because this is not a bug in the SeleniumLibrary, there is not anything to fix in the SeleniumLibrary.

If this was not about to keyword documentation, please clarify the issue.

Because this is a bug in the RIDE, I am going to close the issue. Also if this was not about keyword documentation, please clarify the issue and we will consider opening the issue.

**Closed as completed by aaltat** 2020-06-22 05:57 UTC

**Comment by HelioGuilherme66** [comment] 2020-06-22 09:56
@aaltat This reporter did not even cleared the Issue template hints, I find this offensive ;).
@Pallaviayalureddy There is a workaround to solve this problem in RIDE's project FAQ.

**Comment by Pallaviayalureddy** [comment] 2020-06-22 11:47
Uninstalled seleniumLibrary and installed again now Openbrowser keyworkd working fine
