### ISSUE TITLE
The Wait Until * keywords don't support a None value for the error parameter

### ISSUE THREAD

**Issue by tminakov** [robotframework/SeleniumLibrary#1733] opened 2021-06-09 10:35 UTC
## Steps to reproduce the issue

```
*** Settings ***
Library     SeleniumLibrary

*** Test Cases ***
Test
    Open Browser  url=https://github.com/  browser=Chrome

    Run Keyword And Expect Error        Element * not visible after *
            ...     Wait Until Element Is Visible    locator=xpath://div[@id="nosuchelement"]   timeout=200 milliseconds 

    # the previous call passes, the following - not:

    Run Keyword And Expect Error        Element * not visible after *
            ...     Wait Until Element Is Visible    locator=xpath://div[@id="nosuchelement"]   timeout=200 milliseconds     error=${None}
    # the failure is
    # Expected error 'Element * not visible after *' but got 'None'.

    [Teardown]      Close Browser
```
## Error messages and additional information

The issue is applicable to all `wait_until_*()` methods in the `keywords\waiting.py` file; apparently the type hinting makes Robot Framework itself to cast the value to str - once the value is passed as a method argument, it's already a string.

## Expected behavior and actual behavior

Passing a `${None}` argument to `error` should be equivalent as not setting a value at all, leaving it to default. But it's actually substituted with the string representation, e.g. `"None"`

## Attempted workarounds
Changing the hint to `Union[str, None]`, `Union[None, str]`  - no luck, still the same unexpected behavior.

## Environment

Browser: Not important (reproduced with Chrome v91.0.4472.77)
Browser driver: Not important (reproduced with chromedriver v91.0.4472.19)
Operating System: Win 10, AWS Linux, Ubuntu 18.04
Libraries
- Robot Framework: 4.0.3
- Selenium: 3.141.0
- SeleniumLibrary: 5.1.3
- Interpreter: py3.7.8

**Comment by pekkaklarck** [comment] 2021-06-09 13:21
Does this happen also without Run Keyword And Expect Error?

**Comment by tminakov** [comment] 2021-06-09 13:31
Yep, it does - `error` is once again str type, value: "None".  
I've used the `Run Keyword And Expect Error` just for easier illustration.

**Comment by pekkaklarck** [comment] 2021-06-10 08:46
I can reproduce the problem. I also tested that same argument `error: Optional[str] = None` works fine with a normal library. Based on this I believe the issue is in Python Library Core that's responsible on providing type information from SL to RF. If that's the case, then the problem should be fixed there. In the worst case the dynamic library API doesn't support type information like this and we need to enhance it before we can fix the issue in Python Library Core. Do you @aaltat have time to investigate is the issue in lib core?

**Comment by aaltat** [comment] 2021-06-10 12:16
I can take a look, most likely this week.

**Comment by aaltat** [comment] 2021-06-10 21:31
New release of PLC is made which should fix this problem. Please update PLC and give it a new try.

**Comment by pekkaklarck** [comment] 2021-06-10 21:35
Doesn't upgrading SL also upgrade dependencies?

**Comment by aaltat** [comment] 2021-06-11 05:29
It depends on the package manager and how package manager is run/configured. But I think that by default pip will upgrade the dependencies.

**Comment by tminakov** [comment] 2021-06-11 11:12
Confirmed, the issue is **fixed with PLC v3.0.0** - the argument is now `None` type inside the mehtod.

A couple of observations: 

- Upgrading SL with pip from 4.5.0 to 5.1.3 did not upgrade PLC (the PLC version 2.2.1 brought by SL 4.5.0 also satisfies 5.1.3, so...); clean install naturally gets 3.0.0.
- I think I've read somewhere an argument "None" as a string will be cast to the `None` type automatically (guess - by PLC?). I don't see this happening in PLC v3.0.0 - it remains a string, with that value. If my memory serves me wrong, ignore this :)

Thank you for the fast turnaround.

**Comment by pekkaklarck** [comment] 2021-06-11 11:51
If type is `Union[str, None]`, string `None` isn't converted because the type allows strings.

**Comment by aaltat** [comment] 2021-07-15 06:51
Because this is fixed in PLC side, closing issue.

**Closed as completed by aaltat** 2021-07-15 06:51 UTC
Labels: bug, priority: high, acknowledge
