### ISSUE TITLE
Choose File keyword incorrectly checks file path when running on a remote machine

### ISSUE THREAD

**Issue by technigirl** [robotframework/SeleniumLibrary#1551] opened 2020-02-06 18:01 UTC
The issue is that the Choose File keyword, when run on a remote system, checks the file path when it should not.  It then incorrectly errors out because it cannot find the file, even though the file is present.  When run locally, no error occurs and the keyword works as expected.

## Steps to reproduce the issue

The code I am using is as follows:

choose file     ${ef_image_browse_button}    ${normalized_logo_filepath}

where ${normalized_logo_filepath} in my case is /Users/melissa/repos/qa-automation/Resources/Files/liveoak-logo.png

When I run this on my local machine, it passes.  When I run it on a remote machine (in my case, SauceLabs), it fails as follows:
InvalidArgumentException: Message: invalid argument: File not found : /Users/melissa/repos/qa-automation/Resources/Files/liveoak-logo.png

Expected behavior is that it would pass when run locally and remote.  

Based on the Selenium Library documentation, the first issue is that the file path should not even be checked as of version 4.0.  The second issue is that it is incorrectly flagging the file as not found.  

These are the run commands I am using: 
Local run command:
 python3 -m robot --include email_formatting -V local_variables.py -v ENVIRONMENT:develop --listener Library/debug_listener.py Tests

Remote run command:
python3 -m robot -i email_formatting -V local_variables.py -v ENVIRONMENT:develop -v REMOTE_URL:http://\<username\>:\<key\>@ondemand.saucelabs.com:80/wd/hub -v DESIRED_CAPABILITIES:'name:Win10_Chrome 77,platform:Windows 10,browserName:chrome,version:77.0,idleTimeout:500' Tests

The main difference is that for the remote run, remote_url in Open Browser is set to REMOTE_URL.

I tested this with SeleniumLibrary versions 4.1, 4.2, and 3.2.   4.1 and 4.2 both failed, 3.2 passed with the remote url.  

##Stacktrace:

Traceback (most recent call last):   
File "/usr/local/lib/python3.7/site-packages/SeleniumLibrary/__init__.py", line 470, in run_keyword     return DynamicCore.run_keyword(self, name, args, kwargs)   
File "/usr/local/lib/python3.7/site-packages/SeleniumLibrary/base/robotlibcore.py", line 103, in run_keyword     return self.keywords[name](*args, **kwargs)   
File "/usr/local/lib/python3.7/site-packages/SeleniumLibrary/keywords/formelement.py", line 216, in choose_file     self.find_element(locator).send_keys(file_path)   
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys     'value': keys_to_typing(value)})   
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute     return self._parent.execute(command, params)   
File "/usr/local/lib/python3.7/site-packages/SeleniumLibrary/keywords/browsermanagement.py", line 680, in execute     result = self._base_execute(driver_command, params)   
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute     self.error_handler.check_response(response)   
File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response     raise exception_class(message, screen, stacktrace)

## Environment

Browser: Chrome 77 (Windows) & 79 (Mac)
Browser driver: chromedriver
Operating System: Mac Mojave (local) Windows 10 (remote)
Libraries
- Robot Framework: 3.1.1
- Selenium: 3.141
- SeleniumLibrary: 4.2
- Interpreter: 3.7

**Comment by aaltat** [comment] 2020-02-06 18:51
It's true that file is transferred and it's done by Selenium. But we use custom [local file detector](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/keywords/webdrivertools/sl_file_detector.py#L22), since SeleniumLibrary 4.0. Based on your explanation, it looks like there is a bug somewhere in SeleniumLibrary code. Would it be possible to see simple example which demonstrates the issue. I am specifically interested how you import the library, the exact way (remote url can be dummy value, but all other argument values should be readable from the example) browser is opened and how the keyword is used. Also it would be interesting to see test case run with `--loglevel trace` set from command line and see the all log messages from the failing keyword. Screen shot is fine and please remember to mask sensitive information.

**Comment by aaltat** [comment] 2020-02-07 18:14
I tried the debug problem, but I can not reproduce issue. Therefore I would need more details about your setup. Would it be possible to see simple example which demonstrates the issue. I am specifically interested how you import the library, the exact way (remote url can be dummy value, but all other argument values should be readable from the example) browser is opened and how the keyword is used. Also it would be interesting to see test case run with `--loglevel trace` set from command line and see the all log messages from the failing keyword. Screen shot is fine and please remember to mask sensitive information. The successful [Choose File](https://user-images.githubusercontent.com/2665023/74054146-17debb00-49e6-11ea-9d76-667c9c3f99e1.png) should look something like this and I would be interested to see how yours looks like with logging.

**Comment by aaltat** [comment] 2020-02-19 16:47
Would you have time to provide more details for the issue?

**Comment by technigirl** [comment] 2020-02-19 19:08
@aaltat Yes sorry, I have not had a chance to do this yet, I will try and come up with a short example soon.

**Comment by aaltat** [comment] 2020-03-06 06:43
Closing due inactivity. If there is more information, please report back.

**Closed as completed by aaltat** 2020-03-06 06:43 UTC
