### ISSUE TITLE
Not possible to input text that has ~ ( tilde ) character in it

### ISSUE THREAD

**Issue by mtavi** [robotframework/SeleniumLibrary#712] opened 2016-12-14 12:04 UTC
I found out that it is not possible to have a text, for example a password, with a tilde character in it. Selenium2library does not know how to write the tilde character to the browser.

If Input Text is used as the method of inputting password, in the log.html it is displayed correctly, but if the password is typed into username field to see what it actually types, the tilde is missing.

Running on windows 10, tried and tested on latest Chrome browser and IE 11

decorator (4.0.10)
pip (9.0.1)
robotframework (3.0)
robotframework-selenium2library (1.8.0)
selenium (2.53.1)
setuptools (20.10.1)

ChromeDriver 2.26.436362
IEDriverServer.exe 3.0.0.0 (64-bit)

**Comment by aaltat** [comment] 2016-12-14 16:16
Interesting, tilde is just string as any other character and it should not cause such thing. But world is full of weird bugs, so it's totally possible.

Would it possible to see the log file, with `-loglevel trace` set? It will display more details and shows the characters which selenium is sending to the website?

**Comment by mtavi** [comment] 2016-12-14 16:54
Apparently the character is being sent, but it is not received. Here I tried with a username "tildetilde~user" and the result with -loglevel trace follows

	<msg timestamp="20161214 18:34:39.271" level="TRACE">Arguments: [ ${username}='tildetilde~user' ]</msg>
	<kw name="Input Text" library="Selenium2Library">
	<doc>Types the given `text` into text field identified by `locator`.</doc>
	<arguments>
	<arg>input_0</arg>
	<arg>${username}</arg>
	</arguments>
	<msg timestamp="20161214 18:34:39.271" level="TRACE">Arguments: [ 'input_0' | 'tildetilde~user' ]</msg>
	<msg timestamp="20161214 18:34:39.271" level="INFO">Typing text 'tildetilde~user' into text field 'input_0'</msg>
	<msg timestamp="20161214 18:34:39.272" level="DEBUG">POST http://127.0.0.1:57725/session/6f85dbdab03aba841363f0a21aacc663/elements {"using": "xpath", "sessionId": "6f85dbdab03aba841363f0a21aacc663", "value": "//*[(@id='input_0' or @name='input_0')]"}</msg>
	<msg timestamp="20161214 18:34:39.290" level="DEBUG">Finished Request</msg>
	<msg timestamp="20161214 18:34:39.290" level="DEBUG">POST http://127.0.0.1:57725/session/6f85dbdab03aba841363f0a21aacc663/element/0.29934331134928516-2/clear {"sessionId": "6f85dbdab03aba841363f0a21aacc663", "id": "0.29934331134928516-2"}</msg>
	<msg timestamp="20161214 18:34:39.312" level="DEBUG">Finished Request</msg>
	<msg timestamp="20161214 18:34:39.313" level="DEBUG">POST http://127.0.0.1:57725/session/6f85dbdab03aba841363f0a21aacc663/element/0.29934331134928516-2/value {"sessionId": "6f85dbdab03aba841363f0a21aacc663", "id": "0.29934331134928516-2", "value": ["t", "i", "l", "d", "e", "t", "i", "l", "d", "e", "~", "u", "s", "e", "r"]}</msg>
	<msg timestamp="20161214 18:34:39.424" level="DEBUG">Finished Request</msg>
	<msg timestamp="20161214 18:34:39.425" level="TRACE">Return: None</msg>
	<status status="PASS" endtime="20161214 18:34:39.425" starttime="20161214 18:34:39.271"></status>
	</kw>
	<msg timestamp="20161214 18:34:39.425" level="TRACE">Return: None</msg>
	<status status="PASS" endtime="20161214 18:34:39.425" starttime="20161214 18:34:39.271"></status>
	</kw>

Still, after this has been done the input box reads as follows:

![for_selenium2library_bug_screen](https://cloud.githubusercontent.com/assets/24566474/21191234/20e363d4-c22d-11e6-8a30-963116be84e4.jpg)

**Comment by aaltat** [comment] 2016-12-14 18:42
Perhaps the problem is in the input field and it doesn't allow special characters. Have you tried example with the Google search page to reproduce the problem? If tilde send there successfully then the problem is in the website you are using and not in the library.

**Comment by mtavi** [comment] 2016-12-15 06:57
The same behavior is seen also with Google search. 

Attached is a test that can be used to type text into Google.

[input_tilde.zip](https://github.com/robotframework/Selenium2Library/files/653959/input_tilde.zip)

**Comment by aaltat** [comment] 2016-12-15 07:06
Thank you. Need to try few things but by a quick look on the code side, this could be a problem with the selenium or the underlying browser driver, example ChromeDriver. I will get back on the matter when I have performed some investigation.

In your first post, you did list Chrome and IE driver and therefore can I assume that the problem is reproduced with both browsers?

**Comment by mtavi** [comment] 2016-12-15 09:34
That is correct.
Windows 10

IE 11 + IEDriverServer.exe 3.0.0.0 (64-bit)
Chrome latest + ChromeDriver 2.26.436362

**Comment by aaltat** [comment] 2016-12-18 00:24
For me that test works fine, tilde is written in the search field. I am using: Selenium 3.0.1, Chrome 55.0.2883.87 m (64-bit) and ChromeDriver 2.26.436362

**Comment by aaltat** [comment] 2016-12-19 11:18
@mtavi did your problem get resolved after the selenium update and can we close the issue?

**Comment by mtavi** [comment] 2016-12-21 07:38
@aaltat Unfortunately no, the issue is still present.

pip list
decorator (4.0.10)
pip (9.0.1)
robotframework (3.0)
robotframework-selenium2library (1.8.0)
selenium (3.0.2)
setuptools (20.10.1)

Chrome 55.0.2883.87 m (64-bittinen)
ChromeDriver 2.26.436362

Improved the test a bit, now it fails spectacularly if it doesn't find the text it typed:

[input_and_verify_tilde.zip](https://github.com/robotframework/Selenium2Library/files/665740/input_and_verify_tilde.zip)

**Comment by aaltat** [comment] 2016-12-21 12:09
Are you able to write equivalent test with Python and selenium? If you can't I can do it for you. It reveals is the problem in Selenium2Library side or in the selenium side.

**Comment by mtavi** [comment] 2016-12-21 12:22
I have no experience on that. I did however record the events using selenium IDE, there the tilde character is input properly.

[input_tilde_selenium.txt](https://github.com/robotframework/Selenium2Library/files/666298/input_tilde_selenium.txt)

**Comment by aaltat** [comment] 2016-12-21 13:24
If I recall correctly, it's using inbuilt selenium to run the test and therefore doesn't validate the libraries you are using. I will write you a script but it will be done after Xmas.

Happy holidays

**Comment by emanlove** [comment] 2016-12-21 22:27
@mtavi There is some description in our documentation on how to build a test for selenium (see [here](https://github.com/robotframework/Selenium2Library/blob/master/BUILD.rst#testing-selenium)). The example is using linux as compared to Windows (I wrote it, sorry) and even with this if you haven't done this it can still seem overwhelming. But I wanted to share this if you are interested in trying. We can help you out and I know @aaltat said he could write one too. But hopeful this is helpful and I welcome any feedback if you do try to make the documentation better.

**Comment by aaltat** [comment] 2016-12-22 12:46
Here is the code:
```
from time import sleep

from selenium import webdriver

driver = webdriver.Chrome()
driver.get('https://www.google.fi/')
elem = driver.find_element_by_name('q')
elem.send_keys('name~name')
sleep(2)  # sleep to wait javascript
driver.save_screenshot('C:\\picture.png')  # Replace the path with your needs
driver.close()
```
If you do not use windows, replace the with path suitable for you OS.

When you have run it, tell us how it did go.

**Comment by mtavi** [comment] 2016-12-22 19:44
It went the same way as before, no tilde in sight.

![picture](https://cloud.githubusercontent.com/assets/24566474/21438025/b85a9850-c88f-11e6-8025-ddd283263b72.png)

**Comment by aaltat** [comment] 2016-12-22 20:31
This strongly looks like some sort of environment issue, because it works for me. Unfortunately I don't have any idea what the issue could be. Also it's not a Selenium2Library issue, because it can be reproduced with selenium.

If I would have this issue, I would first try with different selenium and chrome driver versions. If that doesn't help, I would reinstall Python and selenium and see does it resolves the problem. If that doesn't work, then I would try with another PC or with virtual machine and perform a clean install of OS, Python and selenium. But these are just random thoughts, because you know better your system and are better judge what is right course for you.

**Comment by aaltat** [comment] 2017-01-11 13:57
Because this looks like environment issue and because the problem can be reproduced with selenium it's not a Selenium2Library problem. Therefore closing the issue.

If you feel differently, please send an update.

**Closed as completed by aaltat** 2017-01-11 13:57 UTC
