### ISSUE TITLE
Keyword 'Capture Page Screenshot' could not be run on failure: ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by PeterMichalko** [robotframework/SeleniumLibrary#516] opened 2015-09-28 17:54 UTC
The python operation of closing file is causing Selenium2Library.Capture Page Screenshot to fail with message:
"Keyword 'Capture Page Screenshot' could not be run on failure: ValueError: I/O operation on closed file"

It happens after upgrade to 
robotframework (2.9.1) 
robotframework-selenium2library (1.7.4)
with my previously working code with RF 2.8.6 (I guess)

The defect can be reproduced with the code below:

file: test.txt:

**\* Settings ***
Library           Selenium2Library
Variables         Test_Variables.py

**\* Test Cases ***
open web
    Open Browser    http://www.sme.sk    browser=chrome
    Capture Page Screenshot  

and file Test_Variables.py :

out = open('outputdir.tmp','w') # the file is later used by listener
out.write('write something to file')
out.close()

Can anyone take a look why is it happening?

**Comment by PeterMichalko** [comment] 2015-09-28 17:56
When out.close() is commented out, defect does not occure, but functionality of my code is broken.

**Comment by PeterMichalko** [comment] 2015-09-28 18:10
![image](https://cloud.githubusercontent.com/assets/14876759/10144256/f3ebfd5e-661c-11e5-9d9a-95dbfbebce9f.png)

**Comment by aaltat** [comment] 2015-09-28 18:39
This can be also reproduced without Selenium2Library. When I have this test suite:

```
*** Settings ***
Variables    test_variables.py

*** Test Cases ***
Example
    BuiltIn.Get Variables
```

And `test_variables.py` contains this:

```
out = open('outputdir.tmp', 'w')
out.write('write something to file')
out.close()
```

Then I also get `ValueError: I/O operation on closed file` 

The reason why this also manifest by using Selenium2Library is that the discovery of the `${OUTPUT_DIR}` and few other things was changed in [Selenium2Library 1.7.1](https://github.com/robotframework/Selenium2Library/blob/master/CHANGES.rst#171-hotfix) to support Robot Framework 2.9 series. Instead of using Robot Framework internal and not public API, we now use the public API (for few things).

Please report this issue to [Robot Framework issue tracker](https://github.com/robotframework/robotframework/issues). Closed this issue because this is not Selenium2Library issue.

**Closed as completed by aaltat** 2015-09-28 18:39 UTC

**Comment by PeterMichalko** [comment] 2015-09-28 19:00
Thank you Tatu for your quick answer. Reported as https://github.com/robotframework/robotframework/issues/2162
