### ISSUE TITLE
compatibility issue with Firefox newest than v.47

### ISSUE THREAD

**Issue by adamdzwo** [robotframework/SeleniumLibrary#698] opened 2016-12-05 11:24 UTC
Hi,
Robot framework seems to have compatibility issue with Firefox 48, 49 or 50.
Can anyone tell when it will be supported ?

My Robot, etc:
-decorator (4.0.10)
-docutils (0.12)
-fake-factory (0.5.9)
-ipaddress (1.0.16)
-natsort (5.0.1)
-Pillow (2.9.0)
-pip (8.1.2)
-PyAutoGUI (0.9.33)
-PyMsgBox (1.0.3)
-pymssql (2.1.1)
-PyScreeze (0.1.8)
-python-dateutil (2.5.3)
-PyTweening (1.0.3)
-robotframework (3.0)
-robotframework-databaselibrary (0.8.1)
-robotframework-faker (3.0.0)
-robotframework-imagehorizonlibrary (0.1)
-robotframework-ride (1.5.2.1)
-robotframework-selenium2library (1.7.4)
-selenium (2.53.6)
-setuptools (7.0)
-six (1.10.0)
-wheel (0.29.0)
-wrapt (1.10.8)
-xlrd (1.0.0)
-xlutils (2.0.0)
-xlwt (1.1.2)

**Comment by aaltat** [comment] 2016-12-05 13:18
Actually it's a compatibility issue between selenium and Firefox. More details in #676. Also a duplicate of the previous issue

**Closed as completed by aaltat** 2016-12-05 13:18 UTC
