### ISSUE TITLE
Strange exception class for not finding element in waitings

### ISSUE THREAD

**Issue by outcatcher** [robotframework/SeleniumLibrary#997] opened 2017-11-18 11:33 UTC
SeleniumLibrary v. 3.0.0rc1

For waiting keywords implemented using ``waiting._wait_until``, ``ElementNotFound`` is caught and replaced with `AssertionError`. 
It's bit misleading, as ``ElementNotFound`` is pretty expectable error in case element can't be found.

So intuitive (e.g.):
```python
...
self.wait = WaitingKeywords(ctx)
...
try:
    self.wait.wait_until_element_is_not_visible("jquery=.blockPage")
except ElementNotFound:
    pass
```
won't catch exception in this case, as it is instance of `AssertionError`

**Comment by aaltat** [comment] 2017-11-18 12:04
I agree that exception is not in all cases the most describe one. But there are few reasons why exception is `AssertionError`. 

 - Backwards comparability is the one reason, as far I can remember it always have been the same exception.
 - The exception is actually ok for some keywords, example for `Wait Until Page Contains` keyword.

But all that doesn't not mean that it could not be enhanced. We will take your proposal in consideration and perhaps in some point we will do some work, with all exception raised by the library.

**Comment by outcatcher** [comment] 2017-11-18 19:02
Thanks for your reply. Will it be convenient to close this issue in this case?

**Comment by aaltat** [comment] 2017-11-18 19:12
Please leave the issue open. I need to think about the problem for a while and the issue is a good way to remind me about the problem.

**Comment by outcatcher** [comment] 2017-11-18 19:16
Also, as I can see in Selenium2Library v.1.8.0 there was no handling of `ElementNotFound`(have it existed at all?)  or `WebDriverException`.  Keyword `wait_until_element_is_not_visible` is calling `_wait_until_no_error` raising `AssertionError` only on timeout (`_is_visible` inside was using `self._element_find(locator, True, False)` and returning `None` if no element is found). 
Maybe I've missed something though

**Comment by aaltat** [comment] 2017-11-18 19:27
The underlying ElementFinder (which almost all keywords are calling in one way or another) is, in 3.0 and also in earlier releases, calling Selenium `find_elements_*` methods, which will never raise an error from Selenium side (almost true, there are some corner cases when exception is raised from Selenium side). The `find_elements_*` methods are returning list of `WebElements` and if nothing is found, list is empty. Then the SL will raise its own exception based on keyword context and keyword logic. Therefore the SeleniumLibrary doesn't usually need logic to handle Selenium exceptions.

**Comment by aaltat** [comment] 2017-11-18 19:29
Here is a link to the Selenium documentation which explains about the locating elements:  http://selenium-python.readthedocs.io/locating-elements.html

**Comment by aaltat** [comment] 2017-11-20 21:17
Closing on favor of #1000

**Closed as completed by aaltat** 2017-11-20 21:17 UTC
