### ISSUE TITLE
Need a way to specify Firefox binary path while using Open Browser

### ISSUE THREAD

**Issue by naagf5** [robotframework/SeleniumLibrary#1541] opened 2020-01-27 10:07 UTC
Need a way to specify the Firefox binary path.
Current keyword "Open Browser" is not having an option to specify the Firefox binary path. I checked the documentation here http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Open%20Browser

I also tried:
 ${MyDesiredCapabilities}    browserName=firefox     javascriptEnabled=${True}     marionette=${False}    firefox_binary=c:\\FF47\Firefox.exe

Open Browser    url=about:blank    browser=${browser}    desired_capabilities=${MyDesiredCapabilities}

Note: C:\\FF47 is in my PATH environment variable

**Comment by aaltat** [comment] 2020-01-27 10:58
This is already [done](https://github.com/robotframework/SeleniumLibrary/issues/1536)  in the SeleniumLibrary 4.2.0 release candidate 1. Please upgrade your installation and try it out.

Because this is duplicate of #1536 I am closing this issue.

**Closed as completed by aaltat** 2020-01-27 10:58 UTC
