### ISSUE TITLE
Click is "missing" its target and clicks other element

### ISSUE THREAD

**Issue by ripper17** [robotframework/SeleniumLibrary#1317] opened 2019-03-05 10:01 UTC
**Prerequisites**
_- I have searched for similar issues in open tickets and cannot find a duplicate._
#515 looks related, but the last answer there does not solve my issue
#1214 might also be related, but I believe the issue is different to mine

**Steps to reproduce the issue**

```
*** Settings ***
Suite Setup       Run Keywords    SuiteSetup
Library           SeleniumLibrary    timeout=15.0    implicit_wait=0.3    run_on_failure=Nothing

*** Keywords ***
SuiteSetup
    Open Browser    https://dict.leo.org/englisch-deutsch    chrome
    # Window size:
    Set Window Size    1800    1000
    # Clear Localstorage:
    Execute Javascript    window.localStorage.clear();
    # Cookie handling:
    Delete All Cookies
    
TestSetup
    #    How long to wait between each test step?
    Set Selenium Speed    0 seconds
    #    How long to wait until an element is visible, the page contains an element etc.? (for commands like "Wait Until ...")
    Set Selenium Timeout    15 seconds

*** Test Cases ***
TestClick
    #    Load page:
    Go To    https://dict.leo.org/englisch-deutsch/hölle
    #    Check icon "Mehr Informationen":
    Wait Until Element Is Visible    //div[@id='section-subst']//table//tr[1]/td[2]//i[@title='Mehr Informationen']
    Click Element    //div[@id='section-subst']//table//tr[1]/td[2]//i[@title='Mehr Informationen']
    Wait Until Element Is Visible    //div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']
    Wait Until Element Is Visible    //div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']/../button[@title='Close']
    Page Should Contain Element    //div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']/../button[@title='Close']
    Sleep    4
    Click Element    //div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']/../button[@title='Close']
    Element Should Not Be Visible    //div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']
    
```

**Error messages and additional information**
I'm using the RobotFramework to run this test. After reading #515 I tried to add a "name"-attribute to the button (as suggested there) but that doesn't make any difference.
Please note: There will be an advertisement displayed very close to the button and in many cases the "click" actually goes to that ad and opens a new tab with the ad content.

There are rare cases where the test actually works, but it usually doesn't.

**Expected behavior and actual behavior**

Expected: The overlay should close (as with clicking that button manually)

Actual: The overlay is not closed, instead the Ad is "clicked"

**Environment**

Browser: Chromium 72.0.3626.119 Built on Ubuntu, running on Ubuntu 18.04 (64-bit)
Browser driver: ChromeDriver 72.0.3626.119
Operating System: (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: 3.1.1 (installed via pip)
- SeleniumLibrary: 3.3.1 (installed via pip)

I'm running the tests from inside a VM (VirtualBox), Host: Ubuntu 14.04, Guest: Ubuntu 18.04 from inside "ride.py" (version 1.7.3)

**Comment by ripper17** [comment] 2019-03-05 10:09
Debug Info:
```
20190305 11:06:39.581 :  INFO : Current page contains element '//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']/../button[@title='Close']'.
20190305 11:06:43.585 :  INFO : Slept 4 seconds
20190305 11:06:43.587 :  INFO : Clicking element '//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']/../button[@title='Close']'.
20190305 11:06:43.589 : DEBUG : POST http://127.0.0.1:41691/session/4be042da8160059e8fe5f8cd8006890f/elements {"using": "xpath", "sessionId": "4be042da8160059e8fe5f8cd8006890f", "value": "//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']/../button[@title='Close']"}
20190305 11:06:44.525 : DEBUG : http://127.0.0.1:41691 "POST /session/4be042da8160059e8fe5f8cd8006890f/elements HTTP/1.1" 200 103
20190305 11:06:44.534 : DEBUG : Finished Request
20190305 11:06:44.539 : DEBUG : POST http://127.0.0.1:41691/session/4be042da8160059e8fe5f8cd8006890f/element/0.547092867947021-3/click {"sessionId": "4be042da8160059e8fe5f8cd8006890f", "id": "0.547092867947021-3"}
20190305 11:06:45.282 : DEBUG : http://127.0.0.1:41691 "POST /session/4be042da8160059e8fe5f8cd8006890f/element/0.547092867947021-3/click HTTP/1.1" 200 72
20190305 11:06:45.283 : DEBUG : Finished Request
20190305 11:06:45.284 : DEBUG : POST http://127.0.0.1:41691/session/4be042da8160059e8fe5f8cd8006890f/elements {"using": "xpath", "sessionId": "4be042da8160059e8fe5f8cd8006890f", "value": "//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']"}
20190305 11:06:45.502 : DEBUG : http://127.0.0.1:41691 "POST /session/4be042da8160059e8fe5f8cd8006890f/elements HTTP/1.1" 200 103
20190305 11:06:45.505 : DEBUG : Finished Request
20190305 11:06:45.510 : DEBUG : GET http://127.0.0.1:41691/session/4be042da8160059e8fe5f8cd8006890f/element/0.547092867947021-2/displayed {"sessionId": "4be042da8160059e8fe5f8cd8006890f", "id": "0.547092867947021-2"}
20190305 11:06:45.674 : DEBUG : http://127.0.0.1:41691 "GET /session/4be042da8160059e8fe5f8cd8006890f/element/0.547092867947021-2/displayed HTTP/1.1" 200 72
20190305 11:06:45.682 : DEBUG : Finished Request
20190305 11:06:45.686 :  FAIL : The element '//div[contains(@class,'ui-dialog')]//span[text()='LEO: Zusatzinformationen']' should not be visible, but it is.

```

**Comment by aaltat** [comment] 2019-03-05 21:23
I did try your test and I understand your problem. The click misses the button and instead it clicks the ad the background. I can reproduce the problem when running test with Chrome, but with Firefox the test works fine. Because of the different behavior on different browser, this is a browser specific problem and therefore can not be fixed in the SeleniumLibrary side. Instead please raise an issue to the ChromeDriver side: http://chromedriver.chromium.org/help

Because of the above, I am closing the issue.

**Closed as completed by aaltat** 2019-03-05 21:23 UTC

**Comment by ripper17** [comment] 2019-03-06 07:56
Thanks for looking into this. After your hint about the ChromeDriver being "to blame", I've investigated and I'm now pretty sure that the root issue is [Chromedriver unable to click visible element on top of cross domain iframe](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2758) (has already been reported by someone else).
Again, thanks for all your work!

**Comment by aaltat** [comment] 2019-03-06 09:02
No problems and thanks for the clear bug report.
