### ISSUE TITLE
Click element at coordinates keyword ignores given coordinates

### ISSUE THREAD

**Issue by asimell** [robotframework/SeleniumLibrary#804] opened 2017-05-10 10:13 UTC
Giving coordinates for the `Click Element At Coordinates` keyword does not apply the coordinates for the element and instead clicks the element in the middle.

Environment:
Robot Framework 3.0.2
Selenium 3.4.1
Selenium2Library 1.8.0
Firefox ESR 52.1.1
Geckodriver 0.16.1

**Comment by Tattoo** [comment] 2017-05-10 11:06
I can add to this with a reproducible example:

Here's a test site that has a box. When user clicks inside of the box, the page is updated with what coordinates were clicked. Clicking works only inside of the box.

test.html: 
```html
<html>
  <head>
    <title>asdads</title>
    <style>
      #foo {
        width: 100px;
        height: 100px;
        border: 1px solid black;
      }
    </style>
    <script type="text/javascript">
      window.onload = function (){
        document.querySelector('#foo').onclick = function(ev){
          var ev = ev || window.event;
          var target = document.querySelector('#result');
          target.innerHTML = target.innerHTML + '<br />' + ev.clientX + ' ' + ev.clientY;
        }
      }
    </script>
  </head>
  <body >
    <div id="foo"></div>
    <div id="result"></div>
  </body>
</html>
```

Here's a test case that produces the problem: 
```RobotFramework
*** Settings ***
Library   Selenium2Library

*** Test cases ***
TC
    Open browser     http://localhost:8000/test.html
    Click element at coordinates    css=#foo    0   0
    Click element at coordinates    css=#foo    10   10
    Click element at coordinates    css=#foo    1000   1000
    Sleep    2s
    [Teardown]    Close browser
```

Steps to reproduce: 
1. Save the above html to `test.html` and serve it with a webserver ie. `python -m SimpleHTTPServer`. Verify that `http://localhost:8000/test.html` works.
1. Save the above test case and run it: `robot testcase.robot`
1. Observe, that printed coordinates on the page stay the same regardless when:
    * Offsets of zero (0) are given => Library clicks at the center of the element (as it should!)
    * Offsets are given => Library still clicks at the center of the element
    * Offsets that are widely outside of the element boundaries are given => Still at the center of the element. Notice, that previously library threw an error in this case and no longer does that.

**Comment by aaltat** [comment] 2017-05-10 15:26
Ugh

Thank you from the details. Does the problem happen only with Firefox or
can the issue be reproduced with Chrome too?

-Tatu
Send from my mobile

**Comment by Tattoo** [comment] 2017-05-10 18:13
With Chrome, the coordinates seem to work. However, the third case still does not throw an exception -- it just silently does not do anything

![selenium-screenshot-1](https://cloud.githubusercontent.com/assets/280218/25913999/6f9821b6-35c5-11e7-9a4a-e6993e4e1493.png)

**Comment by Tattoo** [comment] 2017-05-10 20:31
The bug affects also IE:

![selenium-screenshot-1](https://cloud.githubusercontent.com/assets/280218/25919895/d19220f2-35d8-11e7-9ed2-5ab886b52608.png)

**Comment by yan0pe00** [comment] 2017-05-10 20:34
I have a similar issue on FF 53.0.2 (32-bit)/selenium==3.4.1/robotframework==3.0.2/geckodriver 0.16.1

Same code works on GC (57.0.2987.133)/ChromeDriver 2.29

Also was working on FF47.01/robotframework==3.0/selenium==2.53.6

**Comment by aaltat** [comment] 2017-05-11 06:15
In practice keyword does this:
```
        element = self.element_find(locator)
        action = ActionChains(self.browser)
        action.move_to_element(element)
        action.move_by_offset(xoffset, yoffset)
        action.click()
        action.perform()
```
Which all is based on selenium API, which makes me suspect that problem lies on the browser driver implementation or perhaps on the selenium side. For the new Firefox it would be good to report the problem for Mozilla and/or selenium. For IE, I think selenium makes the IE driver, so that problem belongs to them.

The above code snippet does not work out of the box and needs some work. Will you need help to produce a running example with selenium only?

**Comment by yan0pe00** [comment] 2017-05-11 19:53
I have opened an issue with Selenium [https://github.com/SeleniumHQ/selenium/issues/4007](url)

**Comment by yan0pe00** [comment] 2017-05-12 18:15
Here is fix https://github.com/SeleniumHQ/selenium/commit/58872c67aa31748d619d120c9c356140c28f0033

**Comment by aaltat** [comment] 2017-05-12 19:00
Thank you from the activity. Because this seems to be problem in selenium and not in Selenium2Library I am closing the issue. Hopefully the next selenium release is soon and the issue gets fixed.

**Closed as completed by aaltat** 2017-05-12 19:00 UTC

**Comment by aaltat** [comment] 2017-05-12 19:23
Forget to say that if you feel differently, please send an update.
