### ISSUE TITLE
Geckodriver error message after running command to update to latest selenium2library version

### ISSUE THREAD

**Issue by chmccue** [robotframework/SeleniumLibrary#681] opened 2016-10-23 18:23 UTC
I'm not sure if this issue should be entered here or in the Gecko Driver issue list.

**Error received:**
WebDriverException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**System information:**
Windows 8.1
Firefox 47.0.1 and 49.0.2
Python 2.7.10
Robot Framework 3.0
Selenium2Library 1.8.0
Selenium 3.0.1

**Description:**
After updating selenium2library via pip last week, my tests stopped working in Firefox.

I  looked for moz:firefoxOptions.binary in Mozilla docs, but was unable to figure out how to set such a capability with Robot Framework.

Other things I have tried:
- Upgraded Firefox from 47 to 49.
- Downloaded latest geckodriver executable and placed it in the python path. Tried both 64 bit and 32 bit versions for windows.
- Renamed geckodriver.exe to wires.exe, which is how I managed to get the Firefox browser working in the past.
- Added new environment variable exclusively for geckodriver.exe.
- Rolled back selenium version to different older versions via pip install selenium==olderversion, and none of them worked.

**Comment by aaltat** [comment] 2016-10-23 18:29
Duplicate of #676 and therefore closing.

**Closed as completed by aaltat** 2016-10-23 18:29 UTC

**Comment by aaltat** [comment] 2016-10-24 08:34
Did forget to say that if need help to actually solve the problem, which can done. Please send the question to the issue #676
