### ISSUE TITLE
How to upload file in robot framework which does not have a input to enter file name.

### ISSUE THREAD

**Issue by Anandh1924** [robotframework/SeleniumLibrary#1103] opened 2018-04-12 02:13 UTC
In my application on clicking browse it use open windows pop-up how to use robot framework in MAC

**Comment by aaltat** [comment] 2018-04-12 05:13
Do not click the `input` element, instead use: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Choose%20File

**Comment by Anandh1924** [comment] 2018-04-12 06:27
<img width="1380" alt="screen shot 2018-04-12 at 11 57 07 am" src="https://user-images.githubusercontent.com/34863572/38659808-ac6d990e-3e48-11e8-89c2-eeb8b1a3d9e9.png">

WebDriverException: Message: unknown error: cannot focus element
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.13.2 x86_64)
------------------------------------------------------------------------------
I am getting above  exception

Wait Until Page Contains     Settings   ${TIMEOUT}
       Click Element                //div[contains(@ng-if,'FormData.profilePicId')]
       Choose File                  //div[contains(@ng-if,'FormData.profilePicId')]    /Users/anandhr/Downloads/Personal Documents/Anandh.jpg
       Click Button                 //button[text()='Upload this image']
       Sleep                        6

**Comment by aaltat** [comment] 2018-04-12 07:12
You do not have a `input` element where to send the path. Instead your application seems to trigger some JavaScript with file upload. Ask from your development what JavaScript you should trigger and how. Then use http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Execute%20Javascript keyword. 

But because this is not a bug in the SeleniumLibrary and strongly looks like support case, I am closing the issue. Support is handled in https://github.com/robotframework/SeleniumLibrary#support

**Closed as completed by aaltat** 2018-04-12 07:12 UTC
