### ISSUE TITLE
Confirm Action Dead Lock in New Window

### ISSUE THREAD

**Issue by cay914** [robotframework/SeleniumLibrary#1006] opened 2017-11-30 11:35 UTC
My web app has some js that like this:
1) main window open child window, via 
window.open(url,..)

2) in child window when I click submit button of the child window that calls function;
function childWindowFunction(){
  top.window.close();
  //call the function of the main window.
}

function mainWindowFunction(){
  //this function does some confirm('') and wait for user input
}
3) when I click OK, the child window will be closed.

about is I do manually, I work fine.

![image](https://user-images.githubusercontent.com/6037435/33428104-9dcee230-d602-11e7-883c-e62b4a14ff68.png)

But when I run this in robot script, my result is a deadlock on the code submitting button of the child window. I think the child windows thread is blocked, and RF is blocked too.
![image](https://user-images.githubusercontent.com/6037435/33428514-22459792-d604-11e7-895a-39e23e97b4e6.png)

Environment:
![image](https://user-images.githubusercontent.com/6037435/33428539-372b9616-d604-11e7-8d24-560a22c8cfa5.png)

![image](https://user-images.githubusercontent.com/6037435/33428558-42186b12-d604-11e7-9d30-6b53c641ac02.png)

I have found when I click the child window in the background, the main window's confirm box dismiss? ?
What is wrong?

Can you give me some guide to test something like this?
Thanks

**Comment by aaltat** [comment] 2017-11-30 12:52
Would you be able to run the test with `--loglevel trace` and `--debugfile debug.log` enable from the test. Also could show us the output from the debug file where the keyword gets stuck. Please remember that this is a public repository and therefore you should remove any sensitive information.

**Comment by cay914** [comment] 2017-12-01 04:06
![image](https://user-images.githubusercontent.com/6037435/33467426-56fb66fc-d68f-11e7-8365-4e6ade4af32d.png)

This is some part of my log file.
Because my log file has some sensitive information, sorry for this inconvenience.
Click element of child window will never finish, until I click it in the background.

**Comment by aaltat** [comment] 2017-12-01 12:26
Ah, now I understand. The `| Click Element | //input... |` keyword is stuck? And when you call the keyword, it also closes the child window, right? This might be problem on Selenium side. Selenium provides a blocking type of API and in practice Selenium listen the `onLoad` event from the browser before it returns (when performing interaction with the elements in the browser). Now if you close the child window before the event is triggered, the Selenium does not never return and therefore the keyword is stuck.

But this is only educated guesses, because I don't see how your application works.  But it certainly looks like that, because in the log file, the timestamp jumps from 10:14:53 to 10:17:13 in the `Click Element` keyword. If this true, instead of clicking the element, you could try to call the underlying JavaScript function which handles the interaction with parent window.

**Comment by cay914** [comment] 2017-12-04 02:19
yes, The | Click Element | //input... | keyword is stuck.
When I click the element, it calls a function that 
window.top.close to close the child window and call the function of the parent window.
Now, parent window does a browser confirm('are you sure submit').
The | Click Element | //input... | keyword is stuck and never return.
So, there is no way to click confirm 's OK of the parent window by robot framework.

I think parent window's confirm box making child window click element keyword block.

**Comment by aaltat** [comment] 2017-12-04 05:40
Instead of clicking the element, you could try to call the underlying JavaScript function which handles the interaction with parent window.

**Comment by aaltat** [comment] 2017-12-10 21:33
Did you happen to find a workaround for your problem? If yes, could you share the solution with us too?

**Comment by cay914** [comment] 2017-12-13 10:31
@aaltat Sorry, I don't want to break my code. Because workaround makes test script complex.
I think robot framework should be powerful. It can do the thing like a human does.
So I develop a simple demo of this issue.
Can you use robot framework to test "choose number" in the demo?
thanks

[demo.zip](https://github.com/robotframework/SeleniumLibrary/files/1555097/demo.zip)

**Comment by aaltat** [comment] 2018-01-30 21:45
And I am sorry that it did took so long to take a look. But I get the same result the `| Click Element | //button |` does get stuck. 

The problem is in Selenium side and is by design. Selenium offers blocking type of API and the action web page performs does not trigger the `onload` event which the Selenium waits. Therefore the Selenium waits forever and test is stuck. If you want to change the behavior, please raise a new issue https://github.com/SeleniumHQ/selenium/issues page. 

As a workaround for your problem, you can to this [test.zip](https://github.com/robotframework/SeleniumLibrary/files/1679483/test.zip). 

But because this is not problem in the SeleniumLibrary and the library works as designed, I am closing the issue.

**Closed as completed by aaltat** 2018-01-30 21:45 UTC
Labels: wont fix
