### ISSUE TITLE
robotframework: Element must be user-editable in order to clear it. when tried to enter date

### ISSUE THREAD

**Issue by sffea12** [robotframework/SeleniumLibrary#1158] opened 2018-07-26 21:53 UTC
Hello, 
I need to enter date , when i do input text   path   date, it doesn't work , message error is displayed : Element must be user-editable in order to clear it
and when i chose the second choice that i click on calendar and i chose date, the calendar is not inspectable.
I can not get the xpath of the calendar - when I right click to inspect element, the calendar disappears.
the is the fiels : (the calendar is not visible in the picture , we need to click on the fields to appear the calendar)
![capturen](https://user-images.githubusercontent.com/41761844/43290607-dd7dac3a-912e-11e8-9416-dd34a34f6d46.PNG)
thank you

**Comment by antonpaa** [comment] 2018-07-27 09:11
This isn't an issue with SeleniumLibrary, but more likely with the webdriver.

When you input text, the previous text content is cleared by design. With date/dateTime and such fields the input can't be made blank. If you can manually input a date to the field, you may still try to use inputs such as `04112018`, `04/11/2018 `and `04-11-2018`. The idea is to fill full the perfect short form which matches the input type (so you wouldn't use `4` as a date, but `04`).

By using e.g. Chrome you can freeze the screen to debug "dynamic" content such as the calendar. E.g. [this](https://stackoverflow.com/a/17932238) explains how to freeze Chrome.

**Comment by aaltat** [comment] 2018-07-27 10:47
I agree that this is not a problem with the SeleniumLibrary. The error is raised by Selenium, which tells that field is read only and therefore it can not clear the text in the element. 

The date picker can be problematic because standard date picker doesn't exist and therefore each implementation is little bit different. But this looks more like a support request than problem with the SeleniumLibrary and therefore I am closing the issue. For support, please see https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support

**Closed as completed by aaltat** 2018-07-27 10:47 UTC
