### ISSUE TITLE
Error when runing install

### ISSUE THREAD

**Issue by lastrecrue** [robotframework/SeleniumLibrary#664] opened 2016-09-08 08:52 UTC
Hi,
I have this stack trace when i try to instal selenium2Library

`$ pip install robotframework-selenium2library
Collecting robotframework-selenium2library
  Using cached robotframework-selenium2library-1.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GVLJ3568\AppData\Local\Temp\pip-build-xpfdv08i\robotframework-selenium2library\setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "C:\Users\GVLJ3568\AppData\Local\Temp\pip-build-xpfdv08i\robotframework-selenium2library\src\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax`

I have Python 3.5.2 and pip 8.1.2

**Comment by aaltat** [comment] 2016-09-08 09:49
Selenium2Library supports current Python 2.6 and 2.7. We are actively working to build Python 3.3+ support but that is not yet ready.

This is a duplicate of #479 and therefore closing the issue.

**Closed as completed by aaltat** 2016-09-08 09:49 UTC
