### ISSUE TITLE
Document method for using waiting for jquery.

### ISSUE THREAD

**Issue by emanlove** [robotframework/SeleniumLibrary#175] opened 2013-03-02 16:49 UTC
Using @peritus  [suggested method](https://github.com/rtomac/robotframework-selenium2library/pull/148#issuecomment-12425477) for waiting for jquery.

```
*** Keywords ***

Wait For Ajax
    Wait for Condition   return window.jQuery.active == 0;
```

See #148

**Comment by aaltat** [comment] 2017-09-13 20:41
Duplicate of #188

**Closed as completed by aaltat** 2017-09-13 20:41 UTC
Labels: duplicate
