### ISSUE TITLE
`Press Key` doesn't send hash character (#) to an input filed

### ISSUE THREAD

**Issue by nnadarajah-resilient** [robotframework/SeleniumLibrary#864] opened 2017-08-16 12:14 UTC
Hey y'all.

I think I may have found a bug on **Press Key** builtin method, reasonably confident :-), details as follows.
http://robotframework.org/Selenium2Library/Selenium2Library.html#Press%20Key

I've been sending keys like below for a input field
**01234\#56789+*** and
**01234#56789+*** and
**0123456789+*#** and
**\\\\35**
**\\35**
**0123456789+*\\35** where **\\35** is decimal value, please see ASCII table.

None of the above inputs for `Press Key` sends the character '#', 
**Input text** builtin method also removes the '#' character.
http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html#Input%20Text
yes **press key** and **Input text** removes hash every single occasion.

**Some Additional questions only if someone could assist.**

I'm sending the character '#' through **execute javascript** like below as a workaround.
`execute javascript  document.getElementsByName('dialNo')[1].value="0123456789+*#"`
I however couldn't provide the control back the webdriver once accomplishing it through java-script.
test keeps failing after completing the above javascript line.

could someone advise a better alternative please.

If I've gotten anything wrong or if you need more info, please let me know

Thanks
Niro

**Comment by aaltat** [comment] 2017-08-16 15:15
The `#` is a special character in Robot Framework and you need escape it: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#escaping

If you still have problem after escaping the `#` could you place provide example which we all can run and see the result. Also telling the selenium, browser and browser driver version is useful information.

**Comment by boakley** [comment] 2017-08-16 15:56
@aaltat: # isn't special except when it's the first character at the start of a cell. It doesn't need to be escaped in the middle of a string.

**Comment by boakley** [comment] 2017-08-16 15:59
For what it's worth, I can't duplicate this issue with Selenium2Library 1.7.4 and selenium 2.53.6. For example, `press key  ${locator}   01234#56789+*`  correctly inserts all of the characters.

**Comment by nnadarajah-resilient** [comment] 2017-08-16 16:01
cheers for the swift response guys, much appreciated.
I'm setting everything up on windows now, let me try chrome & ff driver in windows and see what the outcome is.

the described incident here is experienced in  
ubuntu 16.04, 
ChromeDriver 2.31.488763
geckodriver 0.18.0

I shall report back the status on windows.

**Comment by nnadarajah-resilient** [comment] 2017-08-16 20:53
Hey guys,
Apologies for the delay.
I can confirm this is a linux bug, 
works like a charm in windows 7.

Below are the linux specs where this bug can be reproduced.
ubuntu 16.04,
ChromeDriver 2.31.488763
geckodriver 0.18.0

here is my pip list on linux box

`Here's my pip list on linux box
```
adium-theme-ubuntu (0.3.4)
apipkg (1.4)
Appium-Python-Client (0.24)
beautifulsoup4 (4.4.1)
certifi (2017.7.27.1)
chardet (3.0.4)
coverage (4.4.1)
decorator (4.1.2)
docutils (0.13.1)
execnet (1.4.1)
html5lib (0.999)
idna (2.5)
lxml (3.5.0)
mock (1.0.1)
pip (9.0.1)
py (1.4.34)
pygobject (3.20.0)
pytest (3.1.3)
pytest-cov (2.5.1)
pytest-pythonpath (0.7.1)
pytest-xdist (1.18.2)
requests (2.18.3)
robotframework (3.0.2)
robotframework-appiumlibrary (1.4.4)
robotframework-requests (0.4.7)
robotframework-selenium2library (1.8.0)
sauceclient (1.0.0)
selenium (3.4.3)
setuptools (20.7.0)
six (1.10.0)
unity-lens-photos (1.0)
urllib3 (1.22)
wheel (0.29.0)
````

Hope it helps.
Thanks 
Niro

**Comment by boakley** [comment] 2017-08-16 20:59
how did you confirm it was a linux bug? Do you have the exact same version
of selenium and Selenium2Library on windows and on linux? I'm not able to
reproduce it on my linux box.

**Comment by nnadarajah-resilient** [comment] 2017-08-16 21:06
Yes I do.
here's my pip list on windows

`
apipkg (1.4)
Appium-Python-Client (0.24)
certifi (2017.7.27.1)
chardet (3.0.4)
colorama (0.3.9)
coverage (4.4.1)
decorator (4.1.2)
docutils (0.13.1)
execnet (1.4.1)
idna (2.5)
mock (1.0.1)
pip (9.0.1)
py (1.4.34)
pytest (3.1.3)
pytest-cov (2.5.1)
pytest-pythonpath (0.7.1)
pytest-xdist (1.18.2)
requests (2.18.2)
robotframework (3.0.2)
robotframework-appiumlibrary (1.4.4)
robotframework-requests (0.4.7)
robotframework-selenium2library (1.8.0)
sauceclient (1.0.0)
selenium (3.4.3)
setuptools (28.8.0)
urllib3 (1.22)
`

please let me know if I've gotten anything wrong or need more info.

Thanks
Niro

**Comment by aaltat** [comment] 2017-08-20 20:07
I would check that the selenium, browser and browser driver are exactly the same in both windows and linux. If they  are same then I would report the issue the Selenium issue tracker.

**Comment by aaltat** [comment] 2017-08-31 16:15
Because this seems like a Selenium bug or a OS problem, I am closing this issue because we can not fix it in the SeleniumLibrary side.

**Closed as completed by aaltat** 2017-08-31 16:15 UTC
