### ISSUE TITLE
file name for screenshot on failure should have random string

### ISSUE THREAD

**Issue by vinaybond** [robotframework/SeleniumLibrary#551] opened 2015-12-16 13:25 UTC
When run test via pabot and marge the result, I am facing the issue, that merged files show combine result but screenshot are not visible as combine results file location is different. To solve the problem, I need to copy all the screenshot to the same directory of new result.html file, which I can't as for each test suite, selenium starts file name from screen-shot-1.jpg and so on. If I put that in one directory then it will over write the file.
Can we have a provision that screenshot on failure should have unique name every time (i.e. epoch time in ms, in file name).

**Comment by ombre42** [comment] 2015-12-16 15:14
Duplicate of #268

**Comment by aaltat** [comment] 2015-12-16 15:29
Tackling this problem is easier on the next release. The #504 helps minimise the problem. But @ombre42 is correct, this is duplicate, closed.

**Closed as completed by aaltat** 2015-12-16 15:29 UTC
