### ISSUE TITLE
Input Text Keyword Placing Incorrect String Into A Control

### ISSUE THREAD

**Issue by bjwallen** [robotframework/SeleniumLibrary#669] opened 2016-09-29 01:01 UTC
I am running Robot Framework and Selenium2Library in the following environment:
- Linux version 3.10.0-327.36.1.el7.x86_64 (mockbuild@x86-ol7-builder-01) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) 
- LSB Version:  :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
  Distributor ID: OracleServer
  Description:    Oracle Linux Server release 7.2
  Release:    7.2
  Codename:   n/a
- Google Chrome 53.0.2785.116
- ChromeDriver 2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3)
- Python 2.7.5
- Robot Framework 3.0 (Python 2.7.5 on linux2)
- robotframework-selenium2library-1.8.0

I executed the following .robot test in my environment. The expected string to be input into the username control is not the string that is specified in the ${VALID_USERNAME} variable. See the screen shot for an example. This problems seems to be specific to this configuration since I can execute the test fine on OS X El Capitan.

The log file indicates that the string was input successfully:

```
<kw name="Enter Username" library="loginKeywords">
<arguments>
<arg>${VALID_USERNAME}</arg>
</arguments>
<kw name="Input Text" library="Selenium2Library">
<doc>Types the given `text` into text field identified by `locator`.</doc>
<arguments>
<arg>id=username</arg>
<arg>${username}</arg>
</arguments>
<msg timestamp="20160928 20:58:02.421" level="INFO">Typing text 'bwallen@mythics.com' into text field 'id=username'</msg>
<status status="PASS" endtime="20160928 20:58:02.488" starttime="20160928 20:58:02.421"></status>
</kw>
```

[loginKeywords.txt](https://github.com/robotframework/Selenium2Library/files/499539/loginKeywords.txt)

[login.robot.txt](https://github.com/robotframework/Selenium2Library/files/499541/login.robot.txt)

![incorrecttextinputintocontrol](https://cloud.githubusercontent.com/assets/15219084/18937366/8d8c4af2-85bd-11e6-8550-ceb549f9e841.png)

**Comment by aaltat** [comment] 2016-09-29 06:27
When I have encountered a this type of problem it always have been a problem with the username or with a password being wrong in the other system. If you are sure that the username and password are correct, like actually tried manually input the same values which are in the test case and by using the same url, then I would dig the server logs. I would look for a information which one is incorrect, username or password from the server point of view. If that information is available from logs (or by debugging) then the next interesting questions are why the input value is wrong, is it the same value that was entered by the test and what the correct value would be.

If you cannot access the logs or they don't reveal the required information, the next best thing would be to use proxy, like Fiddler, to see what the browser is actually sending. If the browser is sending the values that the test are inputting the problem lies on the server side. If the values are not the same, then we must do some thinking.

Although I am pointing heavily outside of the Selenium2Library, it doesn't not mean that the problem could not be found from the Selenium2Library. Although this functionality is tested and used a lot, I am pretty sure that the there are corner cases where the library doesn't work correctly and it's possible that you have run into one of those issues.

**Comment by bjwallen** [comment] 2016-09-29 18:06
Thanks for the reply.  In an OS X environment, both Chrome and Firefox tests execute as expected. Further testing in the suspect Linux environment indicates, Firefox/Gecko performs as expected too; therefore, this is not an AuthN problem.

**Comment by aaltat** [comment] 2016-09-29 18:28
Then using proxy tool, to actually see what the browser is sending to the server, might be useful. I can remember a problem with a swing library, that writing to field succeed but when pressing send button nothing was send to the server side. Also sometimes browser can be picky on little things.

**Comment by ombre42** [comment] 2016-09-30 06:48
@aaltat Take another look at the screenshot. The text sent from the selenium client side is not being input into the form as intended, so the information sent to the server via post-back is not right. @bjwallen If you run this test with loglevel DEBUG (use RF argument "--loglevel DEBUG") you should see what Selenium is sending the the driver server (chromedriver in this instance).  In your Python test I bet you are sending the very same request body. So I am thinking that this is perhaps either a problem with focus (if native events are in use), timing ,or some other strange issue. Thanks for providing such detailed environment info!

**Comment by bjwallen** [comment] 2016-09-30 14:19
@ombre42 Thanks for the tip! With --loglevel DEBUG set, it appears that the expected string is being processed.

```
<kw name="Input Text" library="Selenium2Library">
<doc>Types the given `text` into text field identified by `locator`.</doc>
<arguments>
<arg>id=username</arg>
<arg>${username}</arg>
</arguments>
<msg timestamp="20160930 10:02:20.529" level="INFO">Typing text 'bwallen@mythics.com' into text field 'id=username'</msg>
<msg timestamp="20160930 10:02:20.529" level="DEBUG">POST http://127.0.0.1:36319/session/6be981bce36a7229d544ce4a7c0591dc/elements {"using": "id", "sessionId": "6be981bce36a7229d544ce4a7c0591dc", "value": "username"}</msg>
<msg timestamp="20160930 10:02:20.535" level="DEBUG">Finished Request</msg>
<msg timestamp="20160930 10:02:20.535" level="DEBUG">POST http://127.0.0.1:36319/session/6be981bce36a7229d544ce4a7c0591dc/element/0.5110652523267933-1/clear {"sessionId": "6be981bce36a7229d544ce4a7c0591dc", "id": "0.5110652523267933-1"}</msg>
<msg timestamp="20160930 10:02:20.549" level="DEBUG">Finished Request</msg>
<msg timestamp="20160930 10:02:20.549" level="DEBUG">POST http://127.0.0.1:36319/session/6be981bce36a7229d544ce4a7c0591dc/element/0.5110652523267933-1/value {"sessionId": "6be981bce36a7229d544ce4a7c0591dc", "id": "0.5110652523267933-1", "value": ["b", "w", "a", "l", "l", "e", "n", "@", "m", "y", "t", "h", "i", "c", "s", ".", "c", "o", "m"]}</msg>
<msg timestamp="20160930 10:02:20.582" level="DEBUG">Finished Request</msg>
<status status="PASS" endtime="20160930 10:02:20.582" starttime="20160930 10:02:20.529"></status>
</kw>
```

However, the value that can be visibly seen entered into that control is still not as expected. As a result, authentication fails.

**Comment by aaltat** [comment] 2016-10-13 15:05
I don't have any good solution for your problem because from Selenium2Library and also from the selenium Python client point of view, it's sending the correct text to the browser. But after that, there is many moving parts which could go wrong. It could be a timing issue with the page or with the browser. Or it could be a comparability issue between the selenium, Chromedriver or the chrome browser. Which may be difficult to debug.

But have you made progress on the matter?

**Comment by aaltat** [comment] 2016-11-30 07:36
@bjwallen have you progress on the matter?

**Comment by aaltat** [comment] 2016-12-18 21:30
Because this seems to be resolved, closing the issue.

**Closed as completed by aaltat** 2016-12-18 21:30 UTC
