### ISSUE TITLE
Incompatible with Python 3.5.2 under Windows

### ISSUE THREAD

**Issue by sglebs** [robotframework/SeleniumLibrary#618] opened 2016-07-02 14:29 UTC
```
(env) C:\Users\marcio\git\webdriver-python>pip install robotframework-selenium2library
Collecting robotframework-selenium2library
  Downloading robotframework-selenium2library-1.7.4.tar.gz (234kB)
    100% |################################| 235kB 449kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\marcio\AppData\Local\Temp\pip-build-6lgztqfj\robotframework-selenium2library\setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "C:\Users\marcio\AppData\Local\Temp\pip-build-6lgztqfj\robotframework-selenium2library\src\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\marcio\AppData\Local\Temp\pip-build-6lgztqfj\robotframework-selenium2library\
```

**Comment by aaltat** [comment] 2016-07-02 15:14
Duplicate of #479

**Closed as completed by aaltat** 2016-07-02 15:14 UTC
