### ISSUE TITLE
Wait Until Element Is Visible Keyword is unusable if "element is no longer attached to the DOM" error happens

### ISSUE THREAD

**Issue by tarand** [robotframework/SeleniumLibrary#521] opened 2015-10-14 09:16 UTC
My application opens a dialog window when a certain button is pressed. As the opening lasts a while, I need to check for the existence of an element in the dialog. It seems that the "Wait Until Element Is Visible" Keyword is exactly meant for this purpose.
However, in this situation it is very likely that during execution of the "Wait Until Element Is Visible" a "element is no longer attached to the DOM" exception happens. In such a case the keyword will immediately return with a failure, even if the timeout is not reached.
It would be required that this exception is caught and ignored - at least as long as the timeout has not happened.

**Comment by aaltat** [comment] 2015-10-14 10:07
This could be duplicate of #475, providing full stack trace is needed. Also telling version of S2L, selenium and browser is also helpful.

**Comment by tarand** [comment] 2015-10-23 07:25
We are using firefox 29, Seleniuim2Lib 1.7.2, selenium2-python 2.46.1, selenium2-server 2.47.1

Here is the stack. Hope that helps

19:45:04.344    TRACE   Arguments: [ 'provisioningDetailsForm:closeButton' ]  
19:45:04.345    INFO    Clicking element 'provisioningDetailsForm:closeButton'.  
19:45:04.346    DEBUG   POST http://127.0.0.1:4445/wd/hub/session/0e59436b-1fb4-45f1-a94d-c5f104728c8d/elements {"using": "xpath", "sessionId": "0e59436b-1fb4-45f1-a94d-c5f104728c8d", "value": "//_[(@id='provisioningDetailsForm:closeButton' or @name='provisioningDetailsForm:closeButton')]"}  
19:45:04.496    DEBUG   Finished Request  
19:45:04.497    DEBUG   POST http://127.0.0.1:4445/wd/hub/session/0e59436b-1fb4-45f1-a94d-c5f104728c8d/element/1165/click {"id": "1165", "sessionId": "0e59436b-1fb4-45f1-a94d-c5f104728c8d"}  
19:45:04.833    DEBUG   Finished Request  
19:45:05.030    FAIL    StaleElementReferenceException: Message: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'clab1536node04.netact.nsn-rdnet.net', ip: '192.168.1.13', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.7.1.el6.x86_64', java.version: '1.7.0_79'
Driver info: driver.version: unknown
Screenshot: available via screen
Stacktrace:
    at <anonymous class>.fxdriver.cache.getElementAt (resource://fxdriver/modules/web-element-cache.js:9351)
    at <anonymous class>.Utils.getElementAt (file:///tmp/anonymous4848749026382174090webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8942)
    at <anonymous class>.fxdriver.preconditions.visible (file:///tmp/anonymous4848749026382174090webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:9980)
    at <anonymous class>.DelayedCommand.prototype.checkPreconditions_ (file:///tmp/anonymous4848749026382174090webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12626)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h (file:///tmp/anonymous4848749026382174090webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12643)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_ (file:///tmp/anonymous4848749026382174090webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12648)
    at <anonymous class>.DelayedCommand.prototype.execute/< (file:///tmp/anonymous4848749026382174090webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12590)  
19:45:05.030    DEBUG   Traceback (most recent call last):
  File "<string>", line 2, in click_element
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(_args, **kwargs)
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/keywords/_element.py", line 344, in click_element
    self._element_find(locator, True, True).click()
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/webelement.py", line 68, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/webelement.py", line 447, in _execute
    return self._parent.execute(command, params)
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/webdriver.py", line 193, in execute
    self.error_handler.check_response(response)
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by aaltat** [comment] 2015-10-23 14:16
Your stack trace is from Click Element keyword. But it is also true that Wait Until Element Is Visible keyword can also produce the StaleElementReferenceException. In the action type of keywords, like Click Element, I have masked the keyword under the Wait Until Keyword Succeeds keyword. Thant did help me to overcome this error.

Unfortunately fixing Wait\* keywords requires quite big rewrite in the Selenium2Library and will not happen soon.

**Comment by tarand** [comment] 2015-10-23 19:28
Sorry, I picked the wrong stack trace. See below for the right one.
Sure you can workaround this issue by using "Wait until keyword succeeds | Element Should be Visible". But as I said: In this form the "Wait Until Element Is Visible" is not usable. If you cannot fix it, you could better remove it.
Here is the stack trace:
KEYWORD selLib . Wait Until Element Is Visible grantRevokeForm:cancelButton, timeout=${defaultWaitTimeout}, error=no cancel button
Documentation:  

Waits until element specified with `locator` is visible.
Start / End / Elapsed:  20151022 13:26:41.589 / 20151022 13:26:42.736 / 00:00:01.147
00:00:00.239 KEYWORD selLib . Capture Page Screenshot
13:26:41.590    TRACE   Arguments: [ 'grantRevokeForm:cancelButton' | timeout='20' | error='no cancel button' ]  
13:26:41.591    DEBUG   Test timeout 10 minutes active. 525.263 seconds left.  
13:26:41.598    DEBUG   POST http://127.0.0.1:4445/wd/hub/session/c1f8a925-8034-43ac-ac7c-2028ce403f53/elements {"using": "xpath", "sessionId": "c1f8a925-8034-43ac-ac7c-2028ce403f53", "value": "//_[(@id='grantRevokeForm:cancelButton' or @name='grantRevokeForm:cancelButton')]"}  
13:26:41.623    DEBUG   Finished Request  
13:26:41.624    DEBUG   GET http://127.0.0.1:4445/wd/hub/session/c1f8a925-8034-43ac-ac7c-2028ce403f53/element/1712/displayed {"id": "1712", "sessionId": "c1f8a925-8034-43ac-ac7c-2028ce403f53"}  
13:26:41.655    DEBUG   Finished Request  
13:26:41.857    DEBUG   POST http://127.0.0.1:4445/wd/hub/session/c1f8a925-8034-43ac-ac7c-2028ce403f53/elements {"using": "xpath", "sessionId": "c1f8a925-8034-43ac-ac7c-2028ce403f53", "value": "//_[(@id='grantRevokeForm:cancelButton' or @name='grantRevokeForm:cancelButton')]"}  
13:26:42.053    DEBUG   Finished Request  
13:26:42.054    DEBUG   GET http://127.0.0.1:4445/wd/hub/session/c1f8a925-8034-43ac-ac7c-2028ce403f53/element/1712/displayed {"id": "1712", "sessionId": "c1f8a925-8034-43ac-ac7c-2028ce403f53"}  
13:26:42.490    DEBUG   Finished Request  
13:26:42.735    FAIL    StaleElementReferenceException: Message: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'clab1536node04.netact.nsn-rdnet.net', ip: '192.168.1.13', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.7.1.el6.x86_64', java.version: '1.7.0_79'
Driver info: driver.version: unknown
Screenshot: available via screen
Stacktrace:
    at <anonymous class>.fxdriver.cache.getElementAt (resource://fxdriver/modules/web-element-cache.js:9351)
    at <anonymous class>.Utils.getElementAt (file:///tmp/anonymous1291111485830686602webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8942)
    at <anonymous class>.WebElement.isElementDisplayed (file:///tmp/anonymous1291111485830686602webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12168)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h (file:///tmp/anonymous1291111485830686602webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12643)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_ (file:///tmp/anonymous1291111485830686602webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12648)
    at <anonymous class>.DelayedCommand.prototype.execute/< (file:///tmp/anonymous1291111485830686602webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12590)  
13:26:42.736    DEBUG   Traceback (most recent call last):
  File "<string>", line 2, in wait_until_element_is_visible
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/keywords/keywordgroup.py", line 15, in _run_on_failure_decorator
    return method(_args, *_kwargs)
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/keywords/_waiting.py", line 128, in wait_until_element_is_visible
    self._wait_until_no_error(timeout, check_visibility)
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/keywords/_waiting.py", line 237, in _wait_until_no_error
    timeout_error = wait_func(*args)
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/keywords/_waiting.py", line 121, in check_visibility
    visible = self._is_visible(locator)
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/keywords/_element.py", line 727, in _is_visible
    return element.is_displayed()
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/webelement.py", line 326, in is_displayed
    return self._execute(Command.IS_ELEMENT_DISPLAYED)['value']
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/webelement.py", line 447, in _execute
    return self._parent.execute(command, params)
  File "/opt/tex/lib/robotframework-selenium2library/robotframework-selenium2library-1.7.4/Selenium2Library/webdrivermonkeypatches.py", line 11, in execute
    result = self._base_execute(driver_command, params)
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/webdriver.py", line 193, in execute
    self.error_handler.check_response(response)
  File "/opt/tex/lib/selenium2-python/Selenium-2.46.1/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by aaltat** [comment] 2015-10-23 19:40
This is duplicate of the #475. Closing this on favor of #475

**Closed as completed by aaltat** 2015-10-23 19:40 UTC
