### ISSUE TITLE
The keyword "Page Should Not Contain" lasts too long

### ISSUE THREAD

**Issue by louislewatcn** [robotframework/SeleniumLibrary#1193] opened 2018-09-07 09:56 UTC
The keyword "Page Should Not Contain" lasts  30 seconds in my tests.
The same with "Page Should Not Contain Element"

If I need to judge an element is not present, I have to wait for 30 seconds, it is not reasonable

**Comment by aaltat** [comment] 2018-09-07 10:05
Well would you be able to prove your claim? Example could you show an snippet from the log, with `--loglevel trace` set from command line, that shows keyword log messages too. Another way is to write an simplified test, which I can also run.

**Comment by louislewatcn** [comment] 2018-09-07 10:15
Here are my scripts and test results

Page should not contain are marked with red lines

![test script](https://user-images.githubusercontent.com/23356201/45213329-d2d2c880-b2c9-11e8-8a1e-6c7542ce753a.PNG)
![page should not contain](https://user-images.githubusercontent.com/23356201/45213338-d7977c80-b2c9-11e8-8cd7-258f04fcec4a.PNG)

**Comment by aaltat** [comment] 2018-09-07 10:18
Run the test with `--loglevel trace` set from the command line.

**Comment by louislewatcn** [comment] 2018-09-07 10:28
UPDATED
i run test from scripts not command line

    run(TEST_SCRIPTS_INFO["PATH"],
        test=TEST_SCRIPTS_INFO["TEST_NAME"],
        variable=robot_test_variables,
        output=INNER_TEST_PARAMETERS["TEST_RESULT_DIR"]+"output.xml",
        log=INNER_TEST_PARAMETERS["TEST_RESULT_DIR"]+"log.html",
        report=None,
        loglevel="trace"
        )

![page should not contain](https://user-images.githubusercontent.com/23356201/45213967-b768bd00-b2cb-11e8-9744-d62346a3f86c.PNG)

**Comment by louislewatcn** [comment] 2018-09-07 10:34
I HAVE 2 resource files
basic_selenium_key_words.robot
pogo_common_key_words.robot
both import     SeleniumLibrary
*** Settings ***
   **Library             SeleniumLibrary**

In my test file , AddAndRemoveFriends.robot
I import selenium and the source files
*** Settings ***
   **Resource  ./pogo_common_key_words.robot
      Library             SeleniumLibrary    screenshot_root_directory=${TEST_RESULT_DIR}${TESTSCRIPT_ID}     implicit_wait=30.0**

**Comment by aaltat** [comment] 2018-09-07 11:09
The imports in Robot Framework are global. They are not resource or test specific. Therefore the last import wins and sets the implicit_wait to 30 seconds. This means that Selenium will wait 30 seconds element to appear before it returns.

To fix your problem:
1) Import Selenium library only one time
2) Change implicit wait only when needed with: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Set%20Selenium%20Implicit%20Wait Also

Because SeleniumLibrary is working as designed and problem is in test data, I am closing this issue.

**Closed as completed by aaltat** 2018-09-07 11:09 UTC

**Comment by louislewatcn** [comment] 2018-09-07 13:59
thanks for you help
