### ISSUE TITLE
Unable to scroll using python + robot framework

### ISSUE THREAD

**Issue by abhi2717** [robotframework/SeleniumLibrary#1227] opened 2018-10-31 07:55 UTC
Below attached the  code as well as report
unable to find the solution on blog's; 
1. here is **pip freeze:**
Appium-Python-Client==0.29
Appium-UIAutomation==0.1.0
atomicwrites==1.2.1
attrs==18.2.0
colorama==0.4.0
decorator==4.3.0
docutils==0.14
funcsigs==1.0.2
kitchen==1.2.5
more-itertools==4.3.0
pathlib2==2.3.2
pluggy==0.8.0
py==1.7.0
pytest==3.9.3
robotframework==3.0.4
robotframework-appiumlibrary==1.4.6
robotframework-extendedselenium2library==0.9.2
robotframework-selenium2library==1.8.0
robotframework-seleniumlibrary==2.9.2
scandir==1.9.0
selenium==3.8.0
six==1.11.0
urllib3==1.24
virtualenv==16.0.0

2. Screenshots:
![1](https://user-images.githubusercontent.com/43001077/47773359-d2760d00-dd0f-11e8-8ff2-04079485f07f.png)
![2](https://user-images.githubusercontent.com/43001077/47773361-d30ea380-dd0f-11e8-8543-a586ce87c53c.png)
![3](https://user-images.githubusercontent.com/43001077/47773363-d30ea380-dd0f-11e8-808a-75f7c54955f1.png)
![4](https://user-images.githubusercontent.com/43001077/47773364-d3a73a00-dd0f-11e8-9ac4-73e9593012f4.png)
![5](https://user-images.githubusercontent.com/43001077/47773365-d3a73a00-dd0f-11e8-94a0-050541423f02.png)

3. Already used **scroll, scroll up & scroll down** keywords but nothing work.
In the report, shows that script was failed due to "no browser is open" ---> not able to understand 
Please suggest.

**Comment by aaltat** [comment] 2018-10-31 08:38
The error is caused that you are calling a SeleniumLibrary keyword when the SeleniumLibrary `Open Browser` keyword is not called. This is not a bug in SeleniumLibrary but a mistake in test and therefore I am closing the issue.

**Closed as completed by aaltat** 2018-10-31 08:38 UTC

**Comment by abhi2717** [comment] 2018-10-31 09:29
@aaltat  how could we fix this 
as the scenario is to locate the element which is not present on the view of the screen. As I had tested with appium keywords i.e. scroll, scroll up, scroll down; nothing would happen.

**Comment by aaltat** [comment] 2018-10-31 10:45
You are asking support and issue tracker is reserved for bug reports and enhancements. For support please see: https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst#support
