### ISSUE TITLE
How to get the Web Console data using Selenium Code?

### ISSUE THREAD

**Issue by ram117** [robotframework/SeleniumLibrary#1375] opened 2019-04-23 14:38 UTC
# Prerequisites

- I have searched for similar issues in open tickets and cannot find a duplicate.
- The issue still exists against the latest released version of SeleniumLibrary.
- This is not a usage question or support request. For those, see more details in README.rst: https://github.com/robotframework/SeleniumLibrary#support
- You are not using the Java Selenium2Library: https://github.com/Hi-Fi/robotframework-seleniumlibrary-java
- Remember that this is a public forum, so remember to remove all sensitive
information, like username and password.

# For issues
## Steps to reproduce the issue

Create a simplified example which reproduces the problem. It is good if the example
can be run also by us, but this is not always mandatory.

## Error messages and additional information

If there is an error, run the test with `--loglevel trace` set from command line
and copy paste the full stack trace to the issue. Use https://gist.github.com/ or
similar service for anything that longer than few lines.

Provide other details which might be useful for investigating the issue. Screenshots
from application or from unexpected dialogues are example useful. Sometimes showing
relevant parts of the log.html is useful too.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browser: Name and version (Usually available from the about dialogue.)
Browser driver: Name and version
Operating System: Name and version (Linux, Ubuntu 18.04)
Libraries
- Robot Framework: Version
- Selenium: Version
- SeleniumLibrary: Version
- Interpreter: Name and version  

# Feature requests
Describe the need or the feature you are missing from the SeleniumLibrary. Also it
is useful to understand why you need such feature. Many times, it is useful to provide
few examples for acceptance tests. Try to avoid technical or implementation details,
those will handled later.

This project is not funded by any organisation or company, I do this because I
want to do this on my own free time. Therefore if you want feature be implemented,
the easiest and usually fastest way usually is to provide pull request. See
https://github.com/robotframework/SeleniumLibrary/blob/master/CONTRIBUTING.rst
for mode details about project development.

**Comment by aaltat** [comment] 2019-04-23 15:22
Please change the issue text so that it actually explains the what is the problem or what you want to enhance.

**Comment by ram117** [comment] 2019-04-24 01:47
When we perform something in web, there will be a data coming in the Console.
I want to retrieve that data using selenium

**Comment by aaltat** [comment] 2019-04-24 04:21
Selenium offers an API for it, but the method is not exposed as a keyword. More details in #574

But this is a duplicate of #574 and therefore I am closing this issue.

**Closed as completed by aaltat** 2019-04-24 04:21 UTC
