### ISSUE TITLE
Close Browser does not delete alias

### ISSUE THREAD

**Issue by anton264** [robotframework/SeleniumLibrary#1416] opened 2019-07-26 12:30 UTC
Code
 
```
*** Settings ***
Library           SeleniumLibrary
*** Test Cases ***

Open browser

    Open browser   https://github.com/  alias=zombie
    Go to    http://google.se
    Close Browser

Switch to browser
    Switch browser    zombie
    Go to  http://google.fi
```

Expected: Switch browser should fail.
Actual: Switch browser pass and Go to fail.

Close browser leaves the alias of the browser as a valid session resulting in weird behavior when using switch browser

**Comment by aaltat** [comment] 2019-07-26 14:25
This is true and by design, there is even test for the functionality: https://github.com/robotframework/SeleniumLibrary/blob/master/atest/acceptance/open_and_close.robot Although I agree that design is not the best one, but I don't know why it was made (design is made before I came as a maintainer.) Also users can end into a similar situation by closing the current browser and not opening a new one. I agree that functionality could be enhanced. Example the switch should check that driver is not closed or we could clear delete the alias when browser is closed.

Would you be willing to make an PR to fix the problem?

**Comment by yo-ga** [comment] 2019-10-11 13:04
I think this bug is generated from ConnectionCache in Robotframework. When you remove a connection, they don't remove the alias from a mapping table.

**Comment by aaltat** [comment] 2019-10-11 21:03
I haven't looked where the bug actually is and how it could be fixed. But if you want please take a look.

**Closed as completed** 2019-10-13 19:50 UTC
Labels: bug, rc 1, help wanted, priority: low, acknowledge
