### ISSUE TITLE
WebDriverException: Message: Not a Number

### ISSUE THREAD

**Issue by qitaos** [robotframework/SeleniumLibrary#793] opened 2017-04-12 07:24 UTC
I use robotframework(3.0.2)+Selenium2Library(1.8.1) to run test case. Selenium is 3.3.3, Firefox is 50.0, geckodriver is 0.15.0 win32, System: Win7. When I run the test case, Firefox browser was launched. Then raise "WebDriverException: Message: Not a Number".

I fire a bug for firefox but they don't think so. 

In his opinion, post JSON Object should not contain 'sessionid' key. I don't know how to fix it. 
Is this bug for Selenium2Library or Selenium?

The detail in : [https://github.com/mozilla/geckodriver/issues/633](https://github.com/mozilla/geckodriver/issues/633)

**Comment by HelioGuilherme66** [comment] 2017-04-12 08:11
Please post here a minimal reproducible example. You are showing JSON data, but we need to know what keywords were used, to locate the code. Does that happen with a publicly accessible site?

**Comment by qitaos** [comment] 2017-04-12 09:56
http://www.baidu.com is a publicly accessible site. My test case is very simple, open it and get some webelements.

case:

|    Set Log Level  |  trace |  |
| ---- |---- |---- |
|    open browser  |  http://www.baidu.com/  |  ff|
|    @{aaa}  |  Get Webelements  |  css=input |

I set log level to trace and attach the log.html, you can see the log. Thank you.

[log.html.zip](https://github.com/robotframework/Selenium2Library/files/916100/log.html.zip)

**Comment by aaltat** [comment] 2017-04-12 10:46
If you run the same test by using Chrome do you have a same problem?

**Comment by HelioGuilherme66** [comment] 2017-04-12 11:01
Using below code worked fine
```
Simple
    Set Log Level    trace
    ${caps}=    Evaluate    sys.modules['selenium.webdriver'].DesiredCapabilities.FIREFOX.copy()    sys, selenium.webdriver
    Create Webdriver    Firefox    capabilities=${caps}
    Go To    http://www.baidu.com/
    @{aaa}=    Get Webelements    css=input
    [Teardown]    Close All Browsers
```

Log [log.zip](https://github.com/robotframework/Selenium2Library/files/916259/log.zip)

**Comment by aaltat** [comment] 2017-04-12 11:16
This needs little bit more testing but if selenium 3.3.3 now works with FF 50 and geckodriver 0.15, then we should release new version of Selenium2Library. The new release must support FF before and after the geckodriver.

**Comment by qitaos** [comment] 2017-04-13 03:37
@aaltat the same test running by Chrome or IE has no problem.
@HelioGuilherme66 thanks, the code is ok.
I try to use geckodriver 0.14.0 but still error (Missing 'type' parameter). Maybe FF50 is too high.

**Comment by aaltat** [comment] 2017-04-13 06:07
This could be a bug in the Selenium2Library. It needs more investigation but it definitely looks like the selenium 3.3.3 works with FF 50 and geckodriver 0.15.

But this is a duplicate of #676 and therefore I am closing this issue. If you have more questions, please send update to the #676.

**Closed as completed by aaltat** 2017-04-13 06:07 UTC
