### ISSUE TITLE
Firefox fails to handle window.close()

### ISSUE THREAD

**Issue by xanadiu** [robotframework/SeleniumLibrary#733] opened 2017-01-20 15:28 UTC
This issue is kind of related to #360, but it still affects Firefox; Chrome is working well.

I constructed a minimal working example: Open a web page, click on a link that opens a new window by `window.open()`, and trying to close that new window in 3 variants:

* Variant A: `Close Window` => Firefox fails with "WebDriverException: Message: browser is undefined"
* Variant B: `Click Button` => Firefox hangs (after command execution)
* Variant C: `Click Link` => Firefox fails with "WebDriverException: Message: browser is undefined"

(Variants B/C invoke `onclick="self.close();"`.)

I attached the example HTML+JS and also the output of running all variants with Firefox (always failing) and Chrome (always successful).

I would really appreciate help - be it by pointing me to a structural error in my example or an identification of the source that may be out of my scope (and hopefully be fixed!).

The minimal example test case that I am invoking with pybot including output files:
* [02_micro_example_window_open.txt](https://github.com/robotframework/Selenium2Library/files/719726/02_micro_example_window_open.txt)
* [html example files.zip](https://github.com/robotframework/Selenium2Library/files/719738/html.example.files.zip)
* [Firefox - output, log, geckodriver.zip](https://github.com/robotframework/Selenium2Library/files/719732/Firefox.-.output.log.geckodriver.zip)
* [Chrome - output, log.zip](https://github.com/robotframework/Selenium2Library/files/719733/Chrome.-.output.log.zip)

Setup:
* OS X 10.11.6
* Python 2.7.11
* Robot Framework 3.0
** robotframework-requests 0.4.5
* Selenium2Library 1.8.0
* Selenium 3.0.1
* Firefox 50.1.0
* Chrome 55.0.2883.95

Let me know if you need further information.

Thanks
Michael

**Comment by aaltat** [comment] 2017-01-20 19:15
Most likely this is due #676 and the 676 is caused by selenium and Firefox not working. Because we can't do anything to the problem right now I am closing the issue.

If you feel that problem exists after selenium and Firefox again works without problems please open a new issue.

**Closed as completed by aaltat** 2017-01-20 19:15 UTC

**Comment by xanadiu** [comment] 2017-01-21 13:50
I also took a look at #676 before opening this issue. I opened it to clarify what points cause particular problems as #676 seemed to address a general problem between Selenium and newer Firefox versions.

For me **a lot of functions do work with Firefox** except (at least) the particular ones I mentioned here.

Is there any workaround? Who is the addressee for solving the underlying issues?

**Comment by aaltat** [comment] 2017-01-21 16:15
For now it's best to report the found problems to selenium or/and Mozilla. Once the geckodriver interaction with selenium is mature enough, we (Selenium2Library contributors) can start looking what we need to change in our side. But before it's mature enough, I am not going to anything that involves Firefox. I hope that selenium and Mozilla can sort their problems soon.
