### ISSUE TITLE
v4.4.0 - Keywords not highlighted and no suggestion for them in RIDE editor

### ISSUE THREAD

**Issue by axiom41** [robotframework/SeleniumLibrary#1594] opened 2020-05-06 10:20 UTC
Hello.
After updating robotframework-seleniumlibrary to 4.4.0, many of its keywords seem that are not recognized and “highlighted in blue” in RIDE editor (v1.7.4.2), and keyword suggestion does not work (for example, on “click element”, “Input text”, "Capture Page Screenshot", etc.):

![image](https://user-images.githubusercontent.com/9963199/81165947-27dd4b00-8f93-11ea-9600-babf0dcfe7d0.png)

Test execution seems to work fine anyway, but syntax highlighting and keyword suggestion are too important in test writing.

At the moment, I had to revert to v4.3.0 that works fine:

![image](https://user-images.githubusercontent.com/9963199/81166303-cd90ba00-8f93-11ea-91f3-3aa1e59b4dd0.png)

Could you please check and verify on your side, or provide some workaround to make v4.4.0 working?

Many thanks in advance for your support

Best regards

**Comment by aaltat** [comment] 2020-05-06 10:37
In Robot Framework 3.2 the dynamic library API [get_keyword_arguments](https://github.com/robotframework/robotframework/issues/3514) changed and SeleniumLibrary 4.4, by [PythonLibCore changes](https://github.com/robotframework/PythonLibCore/blob/master/docs/PythonLibCore-2.0.1.rst#enhance-get_keyword_arguments-to-support-new-format-in-rf-32-27), use the changed format if RF 3.2 or greater is used. This is RIDE specific problem, please report the problem in RIDE issue tracker. Closing this issue.

**Closed as completed by aaltat** 2020-05-06 10:37 UTC

**Comment by pekkaklarck** [comment] 2020-05-06 12:49
If I understand this right, this problem is due to RIDE using bundled RF 3.0.x and PythonLibCore dropping RF 3.0 support. Was there @aaltat some big concrete benefit of not supporting RF 3.0? If not, and that's the only problem with RIDE, I'd be willing to add its support back. Ping @HelioGuilherme66.

**Comment by aaltat** [comment] 2020-05-06 13:03
RIDE internally uses 3.1.2, but even that does not help, because change is between [RF 3.1 and 3.2](https://github.com/robotframework/PythonLibCore/blob/master/src/robotlibcore.py#L242-L245). 

The RF 3.1 offers [automatic argument conversion](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#automatic-argument-conversion), which allows benefits for the users, example most likely https://github.com/robotframework/SeleniumLibrary/issues/1021 is now fixed or it is fixed afte adding type hints (should test that one tough.) Adding support for 3.0 removes automatic argument conversion support. 

There are workarounds in RIDE side. Example users can generate the keyword documentation and configure RIDE use the keyword documentation instead of reading it from the dynamic library API.

**Comment by pekkaklarck** [comment] 2020-05-06 13:10
Quick comments:
- I totally understand SL supporting only RF 3.1+ to be able to use automatic type conversion. PythonLibCore could still support RF 3.0.
- It would be trivial to change the code you linked to return `[('name', 'default')]` with RF 3.2+ and `['name=value']` with earlier. At the moment it returns `['name=value']` _only_ with RF 3.1 when it should do that with RF < 3.2. I'm happy to do that change.
- Automatic conversion probably doesn't help with #1021 because RF only does that if given arguments are strings. This could be changed but it would be RF 3.3 (or 4.0) feature.

**Comment by aaltat** [comment] 2020-05-06 13:20
1) PythonLibCore supporting RF 3.0 would need extra testing and most likely changes in the code base. Not doing that automatically, unless there is need from the community. 

2) That code already takes the RF version in consideration and converts default arguments to correct format based on the RF version. I think the problem is that RIDE expects the arguments to be always in RF 3.1 format, regardless the RF version

3) This should return: `def example_keyword(count: int)` `count` as integer and it will fix the problem in #1201.

**Comment by pekkaklarck** [comment] 2020-05-06 13:40
It seems I've misunderstood something here. If user has RF 3.2 installed, SL will return args in `[('name', 'default')]` format regardless on what RF version RIDE has bundled in. What RF versions PLC supports doesn't affect that. I agree this is something that should be fixed on RIDE's side. A simple change is converting arguments got from dynamic libs in `[('name', 'default')]` format to `['name=default']` and then handling them as earlier.

But it seems that you have Tatu also misunderstood something with #1021 and/or argument conversion. The point with #1021 is to have a keyword like

```python
def example(text: str):
    print(text.upper())
```

and then call it like
```
Example    ${1}
```

but unfortunately that doesn't work because argument conversion is done only if the [given argument is a string](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#supported-conversions). We cannot change that in the general case, but converting non-string arguments to strings when the type is `str` could be considered.

**Comment by aaltat** [comment] 2020-05-06 13:47
Yes, I did miss read #1021 I though it was from `str` to `int`. Sorry about that.

**Comment by pekkaklarck** [comment] 2020-05-06 13:56
No worries. Plenty of misunderstandings here. :smiley:

**Comment by aaltat** [comment] 2020-05-06 13:57
Did think about easy fix in SL side. Instead of hard coding PythonLibCore in the SeleniumLibrary source, we could have PythonLibCore as a dependency. That would require back porting some setup.py changes and releasing PythonLibCore 1.0 (the currect one is 2.0.1) from a branch. But I do not know is that worth of the effort and will it confuse users even more.

**Comment by pekkaklarck** [comment] 2020-05-06 14:05
I don't think that's worth the effort. RIDE should be fixed to handle `[('name', 'default')]` syntax with dynamic libraries (robotframework/robotframework#3514) in general.
